In [2]:
#importing libraries
import numpy as np
import pandas as pd
import math

In [78]:
#program to create an ANN with back propogation algorithm
class ANN:
    
    def __init__(self,X,y,w):
        self.X=X
        self.y=y
        self.w=w
        
    def weights(self):
        num_of_features=self.X.shape[1]
        rows = self.X.shape[0]
        cols = self.X.shape[1]
        z = np.zeros((rows, cols))
        for i in range(num_of_features):
            z[:,i]=self.X[:,i]*self.w[i]
        return z
    
    def sigmoid(self):
        z=self.weights()
        return 1/(1+np.exp(-z))
    
    def loss(self):
        sigmoid_array = self.sigmoid()
        y_pred = sigmoid_array[:, 0]
        eps=1e-10
        loss=- (1/5) * np.sum((self.y * np.log(y_pred+eps)) + (1 - self.y) * np.log(1 - y_pred+eps))
        return loss
    
    def back_prop(self,n):
        loss=self.loss()
        y1=[]
        epoch=1
        for i in range(len(self.w)):
            self.w[i]=(self.w[i] - (n*loss/self.w[i]))
        return self.w
            

In [3]:
df1=pd.read_excel('test_data.xlsx')
df1.head()

f1  f2  f3  Y
0  23  12  15  0
1  24  33  16  1
2  25  12  23  1
3  25  11  24  0
4  26  24  25  1

In [4]:
X=np.array(df1[['f1','f2','f3']])
y=np.array(df1[['Y']])
y=y.ravel()

In [79]:
rows = 5
cols = 3
z = np.zeros((rows, cols))
w=[4,3,2]

In [88]:
a=ANN(X,y,w1)
z1=a.weights()
l1=a.loss()
w1=a.back_prop(0.1)
l1

[[ 61.48206451  10.44708683 368.69506416]
 [ 64.15519775  28.72948877 393.2747351 ]
 [ 66.82833099  10.44708683 565.33243171]
 [ 66.82833099   9.57649626 589.91210265]
 [ 69.50146423  20.89417365 614.49177359]]
[1. 1. 1. 1. 1.]
[[ 61.48206451  10.44708683 368.69506416]
 [ 64.15519775  28.72948877 393.2747351 ]
 [ 66.82833099  10.44708683 565.33243171]
 [ 66.82833099   9.57649626 589.91210265]
 [ 69.50146423  20.89417365 614.49177359]]
[1. 1. 1. 1. 1.]


9.210340371916184

In [89]:
w1

[2.328581002744751, -0.18735109745463208, 24.5421995699276]